# Exported from:        http://digitalai.wureachprod.awswuintranet.net/
# Release version:      25.1.1-512.313
# Date created:         Fri Sep 26 08:36:49 GMT 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials
spec:
- template: Trigger-Ansible-JobTemplate
  scheduledStartDate: 2024-11-07T03:30:00Z
  phases:
  - phase: New Phase
    tasks:
    - name: Trigger Ansible JT
      type: ansibleController.launchAndWait
      ansibletower: AnsibleDR
      job_template_id: "1288"
      extra_vars: "{     \"number\": \"${ CRnumber }\",     \"user\": \"${ user}\"\
        \   }"
      max_retries: "20"
      wait_interval: "30"
  variables:
  - type: xlrelease.StringVariable
    key: user
    label: user
    value: srinu.talari@wu.com
  - type: xlrelease.StringVariable
    key: CRnumber
    label: Extra_vars
    description: "A string that represents a JSON or YAML formatted dictionary (with\
      \ escaped parentheses) which includes variables given by the user, including\
      \ answers to survey questions"
  riskProfile: Default risk profile
  author: admin
