# Exported from:        http://digitalai.wureachprod.awswuintranet.net/
# Release version:      25.1.1-512.313
# Date created:         Fri Sep 26 08:36:49 GMT 2025

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Samples & Tutorials
spec:
- template: DevOps_Test_job
  scheduledStartDate: 2024-12-06T03:30:00Z
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
  author: admin
